name: 'Post AI Comment (Enhanced)'
description: 'Post clean, processed AI analysis comments to PRs with output validation'
inputs:
  workflow-type:
    description: 'Type of AI workflow'
    required: true
  result-file:
    description: 'Path to AI analysis result file'
    required: false
    default: 'artifacts/ai_analysis_results.json'
  success-message:
    description: 'Success message to show'
    required: false
    default: 'AI analysis completed successfully'

runs:
  using: 'composite'
  steps:
    - name: Process AI Output
      shell: bash
      run: |
        echo "Processing AI output for ${{ inputs.workflow-type }}..."
        mkdir -p artifacts
        
        if [ -f "${{ inputs.result-file }}" ]; then
          echo "Found AI result file: ${{ inputs.result-file }}"
          python3 .github/scripts/process_ai_output.py "${{ inputs.result-file }}"
        else
          echo "AI result file not found, generating fallback comment"
          python3 .github/scripts/generate_fallback_comment.py "${{ inputs.workflow-type }}"
        fi

    - name: Post Comment to PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          try {
            const commentContent = fs.readFileSync('pr_comment.md', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentContent
            });
            console.log('AI comment posted successfully');
          } catch (error) {
            console.error('Failed to post AI comment:', error);
            throw error;
          }

    - name: Generate Workflow Summary
      shell: bash
      run: |
        echo "## AI Enhanced Analysis Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Workflow Type | ${{ inputs.workflow-type }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Status | Completed |" >> $GITHUB_STEP_SUMMARY
        echo "| Output Processing | Applied |" >> $GITHUB_STEP_SUMMARY
        echo "| Comment Posted | Yes |" >> $GITHUB_STEP_SUMMARY