name: 'Post AI Comment (Simple)'
description: 'Post standardized AI analysis comments to PRs using JavaScript'
inputs:
  workflow-type:
    description: 'Type of AI workflow (dependency_analysis, security_audit, etc.)'
    required: true
  result-file:
    description: 'Path to AI analysis result file'
    required: false
    default: 'artifacts/ai_analysis_results.json'
  success-message:
    description: 'Success message to show'
    required: false
    default: 'AI analysis completed successfully'

runs:
  using: 'composite'
  steps:
    - name: 🤖 Generate and Post AI Comment
      shell: bash
      run: |
        echo "🤖 Generating AI comment for ${{ inputs.workflow-type }}..."
        
        # Create artifacts directory if it doesn't exist
        mkdir -p artifacts
        
        # Run universal PR commenter
        node .github/scripts/post_pr_comment.js "${{ inputs.workflow-type }}" "${{ inputs.result-file }}"
        
        if [ $? -eq 0 ]; then
          echo "✅ AI comment generated successfully"
        else
          echo "❌ Failed to generate AI comment"
          exit 1
        fi

    - name: 📝 Post Comment to PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          try {
            // Read the generated comment
            const commentContent = fs.readFileSync('pr_comment.md', 'utf8');
            
            // Post comment to PR
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentContent
            });
            
            console.log('✅ AI comment posted successfully');
          } catch (error) {
            console.error('❌ Failed to post AI comment:', error);
            throw error;
          }

    - name: 📊 Generate Workflow Summary
      run: |
        echo "## 🤖 AI Analysis Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Workflow Type | ${{ inputs.workflow-type }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Status | ✅ Completed |" >> $GITHUB_STEP_SUMMARY
        echo "| Comment Posted | ✅ Yes |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**${{ inputs.success-message }}**" >> $GITHUB_STEP_SUMMARY