#!/usr/bin/env python3
"""
Production Secrets Generator (Phase 7.1)
Generates secure random passwords and secrets for production deployment
"""

import secrets
import string
from pathlib import Path


def generate_secure_password(length: int = 32) -> str:
    """Generate a cryptographically secure random password"""
    alphabet = string.ascii_letters + string.digits + string.punctuation
    # Remove ambiguous characters
    alphabet = alphabet.replace('l', '').replace('I', '').replace('1', '').replace('O', '').replace('0', '')
    password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return password


def generate_secret_key(length: int = 64) -> str:
    """Generate a secure secret key using URL-safe base64"""
    return secrets.token_urlsafe(length)


def generate_all_secrets() -> dict:
    """Generate all production secrets"""
    return {
        # Database passwords (32 chars minimum)
        "POSTGRES_PASSWORD": generate_secure_password(32),
        "POSTGRES_USER": "postgres",  # Keep default user
        
        # Redis password
        "REDIS_PASSWORD": generate_secure_password(32),
        
        # Neo4j password
        "NEO4J_PASSWORD": generate_secure_password(32),
        "NEO4J_USER": "neo4j",  # Keep default user
        
        # Application secrets (64 chars for JWT)
        "SECRET_KEY": generate_secret_key(64),
        "JWT_SECRET_KEY": generate_secret_key(64),
        "JWT_SECRET": generate_secret_key(64),  # Alias
        
        # Encryption key
        "ENCRYPTION_KEY": generate_secret_key(32),
        "AMAS_MASTER_KEY": generate_secret_key(64),
        
        # Grafana password
        "GRAFANA_ADMIN_PASSWORD": generate_secure_password(24),
        
        # FOFA credentials (user must provide)
        "FOFA_EMAIL": "",
        "FOFA_API_KEY": "",
    }


def create_env_template(secrets: dict, output_file: Path):
    """Create .env.production template with generated secrets"""
    template = """# AMAS Production Environment Variables
# Generated by generate_production_secrets.py
# WARNING: Keep this file secure and never commit to version control

# ============================================================================
# APPLICATION
# ============================================================================
ENVIRONMENT=production
LOG_LEVEL=INFO
DEBUG=false

# ============================================================================
# DATABASE PASSWORDS (Generated - CHANGE IF COMPROMISED)
# ============================================================================
POSTGRES_PASSWORD={POSTGRES_PASSWORD}
POSTGRES_USER={POSTGRES_USER}
REDIS_PASSWORD={REDIS_PASSWORD}
NEO4J_PASSWORD={NEO4J_PASSWORD}
NEO4J_USER={NEO4J_USER}

# ============================================================================
# APPLICATION SECRETS (Generated - CHANGE IF COMPROMISED)
# ============================================================================
SECRET_KEY={SECRET_KEY}
JWT_SECRET_KEY={JWT_SECRET_KEY}
JWT_SECRET={JWT_SECRET}
ENCRYPTION_KEY={ENCRYPTION_KEY}
AMAS_MASTER_KEY={AMAS_MASTER_KEY}

# ============================================================================
# MONITORING
# ============================================================================
GRAFANA_ADMIN_PASSWORD={GRAFANA_ADMIN_PASSWORD}

# ============================================================================
# AI PROVIDER API KEYS (Add your actual API keys)
# ============================================================================
CEREBRAS_API_KEY=
NVIDIA_API_KEY=
GROQ2_API_KEY=
GROQAI_API_KEY=
DEEPSEEK_API_KEY=
CODESTRAL_API_KEY=
GLM_API_KEY=
GEMINI2_API_KEY=
GROK_API_KEY=
COHERE_API_KEY=
KIMI_API_KEY=
QWEN_API_KEY=
GPTOSS_API_KEY=
CHUTES_API_KEY=

# ============================================================================
# INTEGRATIONS (Add your actual credentials)
# ============================================================================
FOFA_EMAIL={FOFA_EMAIL}
FOFA_API_KEY={FOFA_API_KEY}
GITHUB_TOKEN=
SLACK_BOT_TOKEN=
N8N_API_KEY=

# ============================================================================
# EXTERNAL SERVICES
# ============================================================================
DATABASE_URL=postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres:5432/amas
REDIS_URL=redis://:{REDIS_PASSWORD}@redis:6379/0
NEO4J_URI=bolt://neo4j:7687
NEO4J_USER={NEO4J_USER}
NEO4J_PASSWORD={NEO4J_PASSWORD}
""".format(**secrets)
    
    output_file.write_text(template)
    print(f"✅ Generated production secrets template: {output_file}")
    print(f"⚠️  WARNING: Keep this file secure! Never commit to version control.")


def create_docker_compose_env(secrets: dict, output_file: Path):
    """Create docker-compose.env file for production"""
    env_content = f"""# Docker Compose Environment Variables for Production
# Generated by generate_production_secrets.py
# Source this file: docker-compose --env-file {output_file.name} up

POSTGRES_PASSWORD={secrets['POSTGRES_PASSWORD']}
REDIS_PASSWORD={secrets['REDIS_PASSWORD']}
NEO4J_PASSWORD={secrets['NEO4J_PASSWORD']}
SECRET_KEY={secrets['SECRET_KEY']}
JWT_SECRET_KEY={secrets['JWT_SECRET_KEY']}
GRAFANA_ADMIN_PASSWORD={secrets['GRAFANA_ADMIN_PASSWORD']}
"""
    
    output_file.write_text(env_content)
    print(f"✅ Generated Docker Compose env file: {output_file}")


def main():
    """Main function"""
    print("🔐 AMAS Production Secrets Generator")
    print("=" * 50)
    
    # Generate all secrets
    secrets = generate_all_secrets()
    
    # Create output directory
    output_dir = Path("config/production")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate .env.production template
    env_file = output_dir / ".env.production"
    create_env_template(secrets, env_file)
    
    # Generate docker-compose.env
    docker_env_file = output_dir / "docker-compose.env"
    create_docker_compose_env(secrets, docker_env_file)
    
    # Print summary
    print("\n" + "=" * 50)
    print("📋 Generated Secrets Summary:")
    print("=" * 50)
    print(f"  Database Password: {secrets['POSTGRES_PASSWORD'][:8]}...")
    print(f"  Redis Password: {secrets['REDIS_PASSWORD'][:8]}...")
    print(f"  Neo4j Password: {secrets['NEO4J_PASSWORD'][:8]}...")
    print(f"  Secret Key: {secrets['SECRET_KEY'][:16]}...")
    print(f"  JWT Secret: {secrets['JWT_SECRET_KEY'][:16]}...")
    print(f"  Grafana Password: {secrets['GRAFANA_ADMIN_PASSWORD'][:8]}...")
    print("\n✅ All secrets generated successfully!")
    print("⚠️  IMPORTANT: Store these secrets securely (password manager, secrets vault)")
    print("⚠️  IMPORTANT: Add .env.production to .gitignore")


if __name__ == "__main__":
    main()

