replicaCount: 3
image:
  repository: ghcr.io/over7-maker/amas
  tag: "v4.0.0-enterprise"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  dashboardPort: 3000
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu: 60
  memory: 70
pdb:
  enabled: true
  minAvailable: 1
security:
  enableTLS: true
  runAsUser: 1000
  fsGroup: 2000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
networkPolicy:
  enabled: true
monitoring:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
extraEnv: []
  # - name: EXTRA
  #   value: "foo"
config:
  LOG_LEVEL: INFO
  SQLALCHEMY_POOL_SIZE: "20"
  SQLALCHEMY_MAX_OVERFLOW: "40"
  SQLALCHEMY_POOL_TIMEOUT: "30"
  SQLALCHEMY_POOL_RECYCLE: "1800"
  UVICORN_WORKERS: "4"
  UVICORN_GRACEFUL_TIMEOUT: "30"
