replicaCount: 6
image:
  repository: ghcr.io/over7-maker/amas
  tag: "v4.0.0-enterprise"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  dashboardPort: 3000
resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 8Gi
autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 50
  cpu: 70
  memory: 80
pdb:
  enabled: true
  minAvailable: 2
security:
  enableTLS: true
  runAsUser: 1000
  fsGroup: 2000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
networkPolicy:
  enabled: true
monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 5s
    labels:
      release: prometheus
