name: 🧠 Master Enhanced AI Orchestrator v3.0

# Revolutionary 4-Layer AI Agent System - Master Coordinator
on:
  # Intelligent triggering based on project state
  push:
    branches: [ main, develop, feature/*, hotfix/* ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  issues:
    types: [ opened, edited, reopened, closed, labeled ]
  issue_comment:
    types: [ created, edited ]
  schedule:
    # Smart scheduling - runs every 6 hours for continuous improvement
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      orchestration_mode:
        description: 'Orchestration Mode'
        required: true
        default: 'intelligent'
        type: choice
        options:
          - intelligent
          - full_analysis
          - emergency_response
          - performance_optimization
          - security_audit
          - documentation_update
      target_components:
        description: 'Target Components (comma-separated)'
        required: false
        type: string
        default: 'all'
      priority_level:
        description: 'Priority Level'
        required: true
        default: 'normal'
        type: choice
        options:
          - low
          - normal
          - high
          - critical
      ai_providers:
        description: 'AI Providers to use (comma-separated)'
        required: false
        type: string
        default: 'all'

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'
  ORCHESTRATOR_VERSION: '3.0'
  AI_SYSTEM_MODE: 'enhanced'
  
  # All 16 AI API Keys for Advanced Failover
  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
  GPT4_API_KEY: ${{ secrets.GPT4_API_KEY }}
  GLM_API_KEY: ${{ secrets.GLM_API_KEY }}
  GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
  KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
  QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GPTOSS_API_KEY: ${{ secrets.GPTOSS_API_KEY }}
  GROQAI_API_KEY: ${{ secrets.GROQAI_API_KEY }}
  CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
  GEMINIAI_API_KEY: ${{ secrets.GEMINIAI_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
  NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
  CODESTRAL_API_KEY: ${{ secrets.CODESTRAL_API_KEY }}
  GEMINI2_API_KEY: ${{ secrets.GEMINI2_API_KEY }}
  GROQ2_API_KEY: ${{ secrets.GROQ2_API_KEY }}
  CHUTES_API_KEY: ${{ secrets.CHUTES_API_KEY }}

jobs:
  # Layer 1: Detection & Analysis - Multi-Agent Intelligence
  layer1_detection_analysis:
    name: "🔍 Layer 1: Detection & Analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      analysis_results: ${{ steps.analysis.outputs.results }}
      critical_issues: ${{ steps.analysis.outputs.critical_issues }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python -m pip install --upgrade pip
          # Install requirements with binary wheel preference

          pip install --prefer-binary -r requirements.txt

          pip install --only-binary=all -r requirements.txt || pip install -r requirements.txt
      
      - name: Run Layer 1 Analysis
        id: analysis
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python .github/scripts/enhanced_code_quality_inspector.py \
            --mode ${{ inputs.orchestration_mode || 'intelligent' }} \
            --priority ${{ inputs.priority_level || 'normal' }} \
            --target ${{ inputs.target_components || 'all' }} \
            --providers ${{ inputs.ai_providers || 'all' }} \
            --use-advanced-manager \
            --output layer1_analysis_results.json
      
      - name: Upload Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: layer1-analysis-results
          path: layer1_analysis_results.json

  # Layer 2: Intelligence & Decision - AI-Powered Decision Making
  layer2_intelligence_decision:
    name: "🧠 Layer 2: Intelligence & Decision"
    runs-on: ubuntu-latest
    needs: layer1_detection_analysis
    timeout-minutes: 25
    outputs:
      decisions: ${{ steps.decision.outputs.decisions }}
      action_plan: ${{ steps.decision.outputs.action_plan }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python -m pip install --upgrade pip
          # Install requirements with binary wheel preference

          pip install --prefer-binary -r requirements.txt

          pip install --only-binary=all -r requirements.txt || pip install -r requirements.txt
      
      - name: Download Layer 1 Results
        uses: actions/download-artifact@v4
        with:
          name: layer1-analysis-results
      
      - name: Run Layer 2 Intelligence
        id: decision
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python .github/scripts/ai_master_orchestrator.py \
            --mode ${{ inputs.orchestration_mode || 'intelligent' }} \
            --priority ${{ inputs.priority_level || 'normal' }} \
            --target ${{ inputs.target_components || 'all' }} \
            --providers ${{ inputs.ai_providers || 'all' }} \
            --use-advanced-manager \
            --input layer1_analysis_results.json \
            --output layer2_decision_results.json
      
      - name: Upload Decision Results
        uses: actions/upload-artifact@v4
        with:
          name: layer2-decision-results
          path: layer2_decision_results.json

  # Layer 3: Execution & Fix - Automated Implementation
  layer3_execution_fix:
    name: "⚡ Layer 3: Execution & Fix"
    runs-on: ubuntu-latest
    needs: [layer1_detection_analysis, layer2_intelligence_decision]
    timeout-minutes: 45
    outputs:
      fixes_applied: ${{ steps.execution.outputs.fixes_applied }}
      success_rate: ${{ steps.execution.outputs.success_rate }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python -m pip install --upgrade pip
          # Install requirements with binary wheel preference

          pip install --prefer-binary -r requirements.txt

          pip install --only-binary=all -r requirements.txt || pip install -r requirements.txt
      
      - name: Download Previous Results
        uses: actions/download-artifact@v4
        with:
          name: layer2-decision-results
      
      - name: Run Layer 3 Execution
        id: execution
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python .github/scripts/enhanced_automated_fixer.py \
            --mode ${{ inputs.orchestration_mode || 'intelligent' }} \
            --priority ${{ inputs.priority_level || 'normal' }} \
            --target ${{ inputs.target_components || 'all' }} \
            --providers ${{ inputs.ai_providers || 'all' }} \
            --use-advanced-manager \
            --input layer2_decision_results.json \
            --output layer3_execution_results.json
      
      - name: Upload Execution Results
        uses: actions/upload-artifact@v4
        with:
          name: layer3-execution-results
          path: layer3_execution_results.json

  # Layer 4: Orchestration & Management - System Coordination
  layer4_orchestration_management:
    name: "🎯 Layer 4: Orchestration & Management"
    runs-on: ubuntu-latest
    needs: [layer1_detection_analysis, layer2_intelligence_decision, layer3_execution_fix]
        if: always()
    timeout-minutes: 20
    if: always()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python -m pip install --upgrade pip
          # Install requirements with binary wheel preference

          pip install --prefer-binary -r requirements.txt

          pip install --only-binary=all -r requirements.txt || pip install -r requirements.txt
      
      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          name: layer3-execution-results
      
      - name: Run Layer 4 Orchestration
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python .github/scripts/multi_agent_orchestrator.py \
            --mode ${{ inputs.orchestration_mode || 'intelligent' }} \
            --priority ${{ inputs.priority_level || 'normal' }} \
            --target ${{ inputs.target_components || 'all' }} \
            --providers ${{ inputs.ai_providers || 'all' }} \
            --use-advanced-manager \
            --input layer3_execution_results.json \
            --output layer4_orchestration_results.json
      
      - name: Generate Final Report
        run: |
        set -e  # Exit on any error
        set -o pipefail  # Exit on pipe errors
          python .github/scripts/comprehensive_audit_engine.py \
            --audit-type comprehensive \
            --create-issues false \
            --notify-on-failure false \
            --output final_orchestration_report.json
      
      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-orchestration-report
          path: final_orchestration_report.json
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let report = '## 🧠 Master AI Orchestrator Results\n\n';
            
            try {
              const data = JSON.parse(fs.readFileSync('final_orchestration_report.json', 'utf8'));
              report += `**Status**: ${data.statistics ? '✅ Completed' : '⚠️ Issues Found'}\n`;
              report += `**Total Issues**: ${data.statistics?.total_issues || 0}\n`;
              report += `**Critical Issues**: ${data.statistics?.critical_issues || 0}\n`;
            } catch (e) {
              report += '**Status**: ⚠️ Report generation failed\n';
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });