name: AI-Driven Threat Intelligence Report Generation

# Automated threat intelligence analysis using multiple AI models
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12 PM UTC
  workflow_dispatch:  # Manual trigger
  issues:
    types: [opened, labeled]
    labels: ['threat-analysis', 'security-alert']

jobs:
  threat-intelligence:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |      python -m ensurepip --upgrade
        python -m pip install --upgrade pippython -m ensurepip --upgrade


        python -m pip install --upgrade pip
        python -m pip install openai requests python-dotenv
    
    - name: Threat Intelligence Analysis
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        GPT4_API_KEY: ${{ secrets.GPT4_API_KEY }}
        GLM_API_KEY: ${{ secrets.GLM_API_KEY }}
        GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
        KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
        QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GPTOSS_API_KEY: ${{ secrets.GPTOSS_API_KEY }}
        REPO_NAME: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        python .github/scripts/ai_threat_intelligence.py
    
    - name: Upload Threat Intelligence Report
      uses: actions/upload-artifact@v4
      with:
        name: threat-intelligence-report
        path: artifacts/threat_intelligence_report.md
        retention-days: 30
    
    - name: Create Threat Intelligence Summary Issue
      if: github.event_name == 'schedule'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'artifacts/threat_intelligence_report.md';
          
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            const summary = report.split('## 📊 Executive Summary')[1]?.split('---')[0] || 'Threat intelligence analysis completed.';
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🛡️ Daily Threat Intelligence Report - ${new Date().toISOString().split('T')[0]}`,
              body: `## Daily Threat Intelligence Summary\n\n${summary}\n\n---\n\n*Full report available in workflow artifacts.*`,
              labels: ['threat-intelligence', 'automated', 'daily', 'security']
            });
          }