name: Emergency Auto Response

on:
  issues:
    types: [opened]

jobs:
  emergency-response:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
    - name: Emergency Auto Response
      uses: actions/github-script@v7
      with:
        script: |
          // Emergency auto-response - no external files needed
          console.log('🚨 EMERGENCY AUTO RESPONSE ACTIVATED');
          console.log('Processing issue #' + context.issue.number);
          
          // Post comment using GitHub's API
          const comment = await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🤖 Emergency Auto Response

Hello @${context.issue.user.login}! 

**Issue Received:**
- **Number**: #${context.issue.number}
- **Title**: ${context.issue.title}
- **Status**: Under Review
- **Priority**: Medium

**What We'll Do:**
1. 📋 **Review**: Analyze your issue
2. 🏷️ **Label**: Add appropriate labels
3. 📅 **Plan**: Determine next steps
4. 🔄 **Update**: Keep you informed

Thanks for contributing to AMAS! 🙏

---
*🤖 Emergency Auto Response System*`
          });
          
          console.log('✅ Comment posted:', comment.data.html_url);
          
          // Add labels
          const labels = await github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['ai-analyzed', 'auto-response', 'emergency-response']
          });
          
          console.log('✅ Labels added:', labels.data.map(l => l.name));
          console.log('🎉 Emergency auto-response completed successfully!');
