name: 🚨 FORCE REAL AI ONLY - Ultimate Fake AI Elimination

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  # All AI provider API keys
  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
  CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
  CODESTRAL_API_KEY: ${{ secrets.CODESTRAL_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
  CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
  GPT4_API_KEY: ${{ secrets.GPT4_API_KEY }}
  GLM_API_KEY: ${{ secrets.GLM_API_KEY }}
  GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
  GROQAI_API_KEY: ${{ secrets.GROQAI_API_KEY }}
  KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
  QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
  GEMINIAI_API_KEY: ${{ secrets.GEMINIAI_API_KEY }}
  GPTOSS_API_KEY: ${{ secrets.GPTOSS_API_KEY }}
  GEMINI2_API_KEY: ${{ secrets.GEMINI2_API_KEY }}
  GROQ2_API_KEY: ${{ secrets.GROQ2_API_KEY }}
  CHUTES_API_KEY: ${{ secrets.CHUTES_API_KEY }}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  force_real_ai_only:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: 📦 Install ALL Dependencies
        run: |
          echo "📦 Installing ALL dependencies for bulletproof AI..."
          python -m pip install --upgrade pip
          pip install aiohttp openai anthropic google-generativeai groq cohere
          pip install mistralai multidict yarl attrs aiosignal frozenlist
      
      - name: 🔍 Check AI Provider Availability
        run: |
          echo "🔍 Checking AI provider availability..."
          
          available_providers=0
          
          if [ -n "$DEEPSEEK_API_KEY" ] && [ ${#DEEPSEEK_API_KEY} -gt 10 ]; then
            echo "✅ DEEPSEEK_API_KEY: Available (${#DEEPSEEK_API_KEY} chars)"
            ((available_providers++))
          else
            echo "❌ DEEPSEEK_API_KEY: Missing or invalid"
          fi
          
          if [ -n "$NVIDIA_API_KEY" ] && [ ${#NVIDIA_API_KEY} -gt 10 ]; then
            echo "✅ NVIDIA_API_KEY: Available (${#NVIDIA_API_KEY} chars)"
            ((available_providers++))
          else
            echo "❌ NVIDIA_API_KEY: Missing or invalid"
          fi
          
          if [ -n "$CEREBRAS_API_KEY" ] && [ ${#CEREBRAS_API_KEY} -gt 10 ]; then
            echo "✅ CEREBRAS_API_KEY: Available (${#CEREBRAS_API_KEY} chars)"
            ((available_providers++))
          else
            echo "❌ CEREBRAS_API_KEY: Missing or invalid"
          fi
          
          if [ -n "$CODESTRAL_API_KEY" ] && [ ${#CODESTRAL_API_KEY} -gt 10 ]; then
            echo "✅ CODESTRAL_API_KEY: Available (${#CODESTRAL_API_KEY} chars)"
            ((available_providers++))
          else
            echo "❌ CODESTRAL_API_KEY: Missing or invalid"
          fi
          
          if [ -n "$COHERE_API_KEY" ] && [ ${#COHERE_API_KEY} -gt 10 ]; then
            echo "✅ COHERE_API_KEY: Available (${#COHERE_API_KEY} chars)"
            ((available_providers++))
          else
            echo "❌ COHERE_API_KEY: Missing or invalid"
          fi
          
          echo "📊 Total available providers: $available_providers/16"
          
          if [ $available_providers -eq 0 ]; then
            echo "🚨 CRITICAL: NO REAL AI PROVIDERS AVAILABLE!"
            echo "❌ Please add at least one valid API key to repository secrets:"
            echo "   - DEEPSEEK_API_KEY"
            echo "   - NVIDIA_API_KEY" 
            echo "   - CEREBRAS_API_KEY"
            echo "   - CODESTRAL_API_KEY"
            echo "   - COHERE_API_KEY"
            echo "   - Or any other supported provider"
            exit 1
          else
            echo "✅ Real AI providers available - proceeding with analysis"
          fi
      
      - name: 🚨 FORCE REAL AI ONLY
        run: |
          echo "🚨 Starting FORCE REAL AI ONLY analysis..."
          
          # Run force real AI only script
          python .github/scripts/force_real_ai_only.py auto_analysis
          
          # CRITICAL: Validate bulletproof real AI was used
          if grep -q '"bulletproof_validated": true' artifacts/force_real_ai_auto_analysis.json; then
            echo "✅ FORCE REAL AI SUCCESS!"
            echo "🤖 Provider used: $(grep -o '"provider": "[^"]*"' artifacts/force_real_ai_auto_analysis.json | head -1)"
            echo "⏱️ Response time: $(grep -o '"response_time": [0-9.]*' artifacts/force_real_ai_auto_analysis.json | head -1)"
          else
            echo "🚨 FORCE REAL AI FAILED - NO FAKE AI ALLOWED!"
            exit 1
          fi
      
      - name: 📝 Post BULLETPROOF REAL AI Results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            try {
              // Read force real AI results
              const data = JSON.parse(fs.readFileSync('artifacts/force_real_ai_auto_analysis.json', 'utf8'));
              
              // HARD REJECTION of fake AI
              if (!data.bulletproof_validated || data.fake_ai_detected) {
                console.log('🚨 FAKE AI DETECTED - REFUSING TO POST FAKE RESULTS!');
                throw new Error('Will not post fake AI analysis results');
              }
              
              const body = `## 🤖 BULLETPROOF REAL AI Analysis

**Status:** ✅ REAL AI Analysis Verified
**Provider:** ${data.provider} (CONFIRMED REAL API CALL)
**Response Time:** ${data.response_time}s (Actual API Response)
**Validation:** Bulletproof verified ✓

### 🔍 REAL AI Analysis Results
${data.analysis}

### 📊 Verification Proof
- **Real AI Verified:** ✅ ${data.real_ai_verified}
- **Fake AI Detected:** ❌ ${data.fake_ai_detected} 
- **Provider Attempt:** ${data.provider_attempt}/${data.total_attempts}
- **Bulletproof Validated:** ✅ ${data.bulletproof_validated}

### 🚫 Fake AI Patterns Blocked
This analysis is **GUARANTEED REAL** - the following fake patterns were blocked:
- ❌ "AI Output Processor" responses
- ❌ "Mock/Fallback" templates  
- ❌ Generic "analysis completed successfully"
- ❌ Identical response times (1.5s, 2.8s, etc.)
- ❌ "Provider: AI System" or "Unknown"

*🤖 GUARANTEED REAL AI - Provider: ${data.provider}*
*This is NOT a template - Actual AI API call performed*
*Generated by Force Real AI Only System v1.0*`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
              
              console.log('✅ BULLETPROOF REAL AI COMMENT POSTED!');
              
            } catch (error) {
              console.log('🚨 ERROR POSTING COMMENT:', error.message);
              throw error;
            }
      
      - name: 🔍 Final Validation
        run: |
          echo "🔍 Final validation - ensuring NO fake AI used..."
          
          fake_detected=false
          
          # Check all artifact files for bulletproof validation
          for file in artifacts/*.json; do
            if [ -f "$file" ]; then
              echo "Checking $file..."
              if ! grep -q '"bulletproof_validated": true' "$file"; then
                echo "🚨 FAKE AI DETECTED in $file"
                fake_detected=true
              fi
            fi
          done
          
          if [ "$fake_detected" = "true" ]; then
            echo "🚨 WORKFLOW FAILED - FAKE AI DETECTED!"
            exit 1
          else
            echo "✅ ALL AI VERIFIED AS REAL!"
          fi