name: Python Dependency Submission

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel pip-tools

      - name: Install dependencies
        run: pip install -r requirements.txt
